"""Default configuration constants for SegmentSpeakerLabeler."""
from typing import Optional

DEFAULT_THRESHOLD_SAME: Optional[float] = None
DEFAULT_THRESHOLD_POSSIBLE: Optional[float] = None
DEFAULT_THRESHOLD_NEW_SPEAKER: Optional[float] = None
DEFAULT_MIN_SEGMENTS_FOR_REFERENCE: int = 2
DEFAULT_MAX_EMBEDDINGS_PER_SPEAKER: int = 50
DEFAULT_TEMPORAL_SMOOTHING_WINDOW: float = 3.0
DEFAULT_TOP_K_SPEAKERS: int = 3
DEFAULT_MIN_SIMILARITY_FOR_LIST: float = 0.15
DEFAULT_CONSOLIDATION_THRESHOLD: float = 0.80
DEFAULT_MATURE_SEGMENT_COUNT: int = 5
DEFAULT_YOUNG_SEGMENT_COUNT: int = 2
DEFAULT_USE_SPEECH_WAVE_FILTERING: bool = True
DEFAULT_MIN_PROMINENCE: float = 0.05
DEFAULT_MIN_EXCURSION: float = 0.04
DEFAULT_MIN_PEAK_PROB: float = 0.9
DEFAULT_MIN_FRAMES: int = 100
DEFAULT_MIN_DURATION_SEC: float = 0.25
DEFAULT_BASELINE_THRESHOLD: float = 0.1
DEFAULT_MIN_SIMILARITY_TO_UPDATE: float = 0.25
